server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql:///orders_db?cloudSqlInstance=project-abbbaa96-84e3-4202-a12:us-central1:free-trial-first-project&socketFactory=com.google.cloud.sql.mysql.SocketFactory
    username: kafkauser
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: order-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: com.spring.kafka.LearningSpringKafka.dto
        spring.json.value.default.type: com.spring.kafka.LearningSpringKafka.dto.OrderEvent

app:
  kafka:
    topic: order-events